### ISSUE TITLE
DDP Connection Idle Disconnect

### ISSUE THREAD

**Issue by mayvn10** [vsivsi/ddp-login#3]
Great package! Currently using it in a project hosted on DO in connection with a meteor app hosted on Galaxy but it seems like if the connection is idle and there are no processes happening, it will disconnect.

We have reconnect measures in place but it continues to disconnect anyway. Are there more ways to keep a sustained connection?

**Comment by vsivsi** [comment]
This isn't a DDP login issue. All this package handles is the authentication exchange. 

Please raise this issue on the appropriate package: https://github.com/oortcloud/node-ddp-client

**Comment by mayvn10** [comment]
Ok transferring now. Thank you.
